version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  AfterInstall:
    - location: code_deploy/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: code_deploy/application_start.sh
      timeout: 300
      runas: ubuntu
