version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: code_deploy/application_stop.sh
      timeout: 300
  BeforeInstall:
    - location: code_deploy/before_install.sh
  ApplicationStart:
    - location: code_deploy/application_start.sh
      timeout: 300
